---
title: "Notes on Employment Barriers"
description: |
  A review of a research paper which offers a new way to empirically evaluate employment barriers
date: 2019-08-04
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
bibliography: biblio.json
categories:
  - policy research
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Overview

* [@FacesJoblessnessCharacterising2016] advances new methods to categorize employment barriers among jobseekers so as to design appropriately tailored activation responses across policy and institutional domains.
* little is known about specific employment barriers at the individual level, instead broad proxies are used to describe populations (NEET, older workers etc)
* instead the authors try a _bottom up_ approach by categorizing and measuring employment barriers
* using _latest class analysis_ (LDA), a clustering method, the authors find more useful groups of jobseekers who share common employment barriers by analyzing the European Union Statisitcs on Income and Living Conditions (EU SILC) [available here](https://ec.europa.eu/eurostat/web/microdata/european-union-statistics-on-income-and-living-conditions) 


### Types of Employment Barriers
* lack of work-relateed capabilities
	* a range of factors that may limit an individuals' capacity to perform a specific task (e.g. lack of educations, skills or work experience, care responsibilities, or health limitations)
* lack of work incentives
	* weak incentives to look for or accept a good job - (e.g. low pay, generous out of work benefits)
* lack of employment opportunities (regional)
	* a small number of vacancies in the labour market segment due to information asymmetries, skills mismatches, discrimination

### Highlights

> "A first step describes a series of employment-barrier indicators at the micro level, comprising three domains: work-related capabilities, financial incentives and employment opportunities" ([ 2016:5](zotero://open-pdf/library/items/JG4RS6CR?page=5))

> "First, standard labour-market statistics provide information about correlates of employment barriers" - "but not about employment barriers as such" - "little is known about what these individual circumstances look like or how they may translate into employment barriers that policies aim to address" - "policy discussions frequently refer to broad groupings of individuals as a short-hand" - "implicit assumption is that these groupings are useful for describing different sets of employment barriers" - "little attempt to systematically assess the specific barriers of policy clients whom AESPs are intended to help" ([ 2016:8](zotero://open-pdf/library/items/JG4RS6CR?page=8))

> "employment barriers that potentially drive poor labourmarket outcomes: (i) a lack of work-related capabilities, (ii) a lack of work incentives and (iii) a lack of employment opportunities" ([ 2016:9](zotero://open-pdf/library/items/JG4RS6CR?page=9))

> "This finding highlights the need for a careful examination of these groups as a basis for suitably targeted and tailored AESPs." ([ 2016:9](zotero://open-pdf/library/items/JG4RS6CR?page=9))

> "Section 2 identifies the sample of interest: individuals with potential labour-market difficulties. Section 3 proposes empirically feasible methods for deriving indicators of different labour market barriers using the information available" ([ 2016:9](zotero://open-pdf/library/items/JG4RS6CR?page=9))

> "Section 4 presents the clustering exercise and discusses results. Section 5 outlines preliminary conclusions and considers possible next steps. A technical annex sets out the conceptual background and the statistical properties of the latent-class method used for the clustering exercise." ([ 2016:9](zotero://open-pdf/library/items/JG4RS6CR?page=9))

> "this paper therefore includes working-age individuals who are entirely out of work (either actively searching for a job or inactive) or whose labour-market attachment is "weak" (Figure 1). "Weak" labour-market attachment can include individuals with unstable jobs working only sporadically, those working persistently with restricted working hours, and those with very low earnings (due to, for example, being partially unpaid, or working informally)" ([ 2016:10](zotero://open-pdf/library/items/JG4RS6CR?page=10))

> "We do not attempt to distinguish between voluntary and involuntary joblessness" ([ 2016:10](zotero://open-pdf/library/items/JG4RS6CR?page=10))

> "20 hours or less a week for one of the following reasons: illness or disability, housework or care duties, absence of other job opportunities, voluntary part-time, other reasons." ([ 2016:15](zotero://open-pdf/library/items/JG4RS6CR?page=15))

> "employment-support measures should closely correspond to the specific drivers behind people's labour-market difficulties" ([ 2016:20](zotero://open-pdf/library/items/JG4RS6CR?page=20))

> "If multiple barriers exist simultaneously, successful interventions are likely to require an appropriate combination, coordination and sequencing of policy measures." ([ 2016:20](zotero://open-pdf/library/items/JG4RS6CR?page=20))

> "illustrations rather than an attempt at a comprehensive list of all indicators" ([ 2016:20](zotero://open-pdf/library/items/JG4RS6CR?page=20))

> "Individuals who would like to work may be unable to provide the type or quantity of labour that is demanded by employers. The resulting mismatch reduces their chances of finding a job, and their productivity while in employment." ([ 2016:22](zotero://open-pdf/library/items/JG4RS6CR?page=22))

> "educational attainment remains strongly linked with productivity and labour market outcomes" ([ 2016:22](zotero://open-pdf/library/items/JG4RS6CR?page=22))

> "The highest educational attainment constitutes the preferred "skills" indicator" ([ 2016:22](zotero://open-pdf/library/items/JG4RS6CR?page=22))

> "Self-reported sickness or disability affect large parts of the working population in EU" ([ 2016:24](zotero://open-pdf/library/items/JG4RS6CR?page=24))

> "disability benefits are at least as common a form of out-of-work support as unemployment benefits" ([ 2016:25](zotero://open-pdf/library/items/JG4RS6CR?page=25))

> "Specifically, following Knudsen et al. (2010), individuals who report some or severe limitations in usual activities are characterized as having a reduced work capacity due to health iss" ([ 2016:25](zotero://open-pdf/library/items/JG4RS6CR?page=25))

> "Care responsibilities can be primary drivers of individuals' inability to participate in the labour market, particularly among women" ([ 2016:26](zotero://open-pdf/library/items/JG4RS6CR?page=26))

> "High-intensity care-giving, in particular, is associated with low labour supply among family carer" ([ 2016:26](zotero://open-pdf/library/items/JG4RS6CR?page=26))

> "when income gain from taking up a job or working more is limited, because net wages are low or because generous out-of-work benefits are withdrawn as people start to work" ([ 2016:27](zotero://open-pdf/library/items/JG4RS6CR?page=27))

> "demand-related constraints in the respective labour market segment" ([ 2016:31](zotero://open-pdf/library/items/JG4RS6CR?page=31))

> "the degree of urbanisation is used instead to capture geographical differences within the country" ([ 2016:31](zotero://open-pdf/library/items/JG4RS6CR?page=31))

> "The probability of facing labour market constrains is estimated by means of a simple regression model for the entire reference population. The estimated parameters are then used to predict the risk of being demand constrained" ([ 2016:32](zotero://open-pdf/library/items/JG4RS6CR?page=32))

> "traditional regression analysis. Regression models would, e.g., show how each barrier in isolation affects the risk of facing potential labour market difficulties while holding all other barriers constant. By contrast, the proposed approach focuses on the interrelations between employment barriers and how they jointly determine observed labour-market outcomes. The focus on joint patterns of employment barriers is relevant as the success of AESPs typically depends on their ability to address real-world combinations of different labour-market obstacles." ([ 2016:33](zotero://open-pdf/library/items/JG4RS6CR?page=33))

> "Tailoring policies to only the most prominent real or assumed barriers facing these groups may therefore not be sufficient for increasing their employment chances." ([ 2016:33](zotero://open-pdf/library/items/JG4RS6CR?page=33))

